### PR TITLE
Javascript cleanup

### PR DESCRIPTION
**Pull request by wormeyman**
Take a look at https://github.com/wormeyman/async-javascript/commits/jsRefactor2 for changes

### CODE REVIEW

**Comment by futtta** [comment]
how does this relate with the UI-changes @wormeyman ?

**Comment by wormeyman** [comment]
Whoops! It is not related which is why it is a separate pull request. The big change is pulling the orange notification into a global function and then having it fade out instead of staying on the screen.

**Comment by futtta** [comment]
wow, this is getting complicated :-)

no, I (@futtta) will review your latest commits and if all OK I'll merge uichange with master.

after that you (@wormeyman ) could re-issue a PR based on the new master (including the uichanges) for the JS cleanup in this PR.

**Comment by wormeyman** [comment]
haha ok ;)

**Comment by futtta** [comment]
do we need/ want the vscode stuff here on git? can you add it to .gitignore?

**Pull request closed without merging**
