### PR TITLE
add is_login() for asyncjsBackendClass.php

### PR DESCRIPTION
**Pull request by alloylab**
please note is_login() was introduced in 6.1.0, it addresses the issue raised here: https://wordpress.org/support/topic/exclude-wp-login-admin-area/

### CODE REVIEW

**Comment by futtta** [comment]
yes but no; I agree frontend AsyncJS should not be active on is_login (although I don't think it is), but I don't think the backend AsyncJS should be active on login pages?

**Comment by alloylab** [comment]
yes frontend AsyncJS is active on the login page... without the modification in the commit the following JS error is thrown in the console, "wp is not defined" with relation to "wp.i18n.setLocaleData( { 'text direction\u0004ltr': [ 'ltr' ] } );" ... an alternative would be the following

`
if (is_admin()) {
    require_once('asyncjsBackendClass.php');
    $ajBackend = new AsyncJavaScriptBackend();
} elseif(is_login()) {
    // Login Page Do Nothing
} else {
    require_once('asyncjsFrontendClass.php');
    $ajFrontend = new AsyncJavaScriptFrontend();
}

`

**Comment by futtta** [comment]
maybe make it

```php
if ( is_admin() ) {
  require_once( 'asyncjsBackendClass.php' );
   $ajBackend = new AsyncJavaScriptBackend();
} elseif ( ! function_exists( 'is_login' ) || ! is_login() ) {
  require_once( 'asyncjsFrontendClass.php' );
  $ajFrontend = new AsyncJavaScriptFrontend();
}
```

if you can adapt your PR like that, I'll be happy to accept & merge :-)

**Comment by alloylab** [comment]
@futtta PR has been updated

**Comment by futtta** [comment]
super. last question; did you test and can you confirm it works as in; 

1. asyncjs is active on frontend?
2. the admin pages work?
3. the login page is left alone?

**Pull request closed without merging**
